package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Credito generated by hbm2java
 */
@Entity
@Table(name = "CREDITO", schema = "PRUEBAH")
@XmlRootElement(name = "credito")
public class Credito implements java.io.Serializable {

	private BigDecimal idCredito;
	private UsuarioDetalle usuarioDetalle;
	private BigDecimal disponible;
	private String tarjetaNom;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public Credito() {
	}

	public Credito(BigDecimal idCredito, UsuarioDetalle usuarioDetalle,
			BigDecimal disponible, String tarjetaNom) {
		this.idCredito = idCredito;
		this.usuarioDetalle = usuarioDetalle;
		this.disponible = disponible;
		this.tarjetaNom = tarjetaNom;
	}

	public Credito(BigDecimal idCredito, UsuarioDetalle usuarioDetalle,
			BigDecimal disponible, String tarjetaNom, Set<Pago> pagos) {
		this.idCredito = idCredito;
		this.usuarioDetalle = usuarioDetalle;
		this.disponible = disponible;
		this.tarjetaNom = tarjetaNom;
		this.pagos = pagos;
	}

	@Id
	@Column(name = "ID_CREDITO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdCredito() {
		return this.idCredito;
	}

	public void setIdCredito(BigDecimal idCredito) {
		this.idCredito = idCredito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_USUD", nullable = false)
	public UsuarioDetalle getUsuarioDetalle() {
		return this.usuarioDetalle;
	}

	public void setUsuarioDetalle(UsuarioDetalle usuarioDetalle) {
		this.usuarioDetalle = usuarioDetalle;
	}

	@Column(name = "DISPONIBLE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getDisponible() {
		return this.disponible;
	}

	public void setDisponible(BigDecimal disponible) {
		this.disponible = disponible;
	}

	@Column(name = "TARJETA_NOM", nullable = false, length = 20)
	public String getTarjetaNom() {
		return this.tarjetaNom;
	}

	public void setTarjetaNom(String tarjetaNom) {
		this.tarjetaNom = tarjetaNom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "credito")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
