package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Directorio generated by hbm2java
 */
@Entity
@Table(name = "DIRECTORIO", schema = "PRUEBAH")
@XmlRootElement(name = "directorio")
public class Directorio implements java.io.Serializable {

	private BigDecimal idDirectorio;
	private UsuarioDetalle usuarioDetalleByFkUsudOri;
	private UsuarioDetalle usuarioDetalleByFkUsudDes;
	private BigDecimal montoAcuerdo;
	private Set<Pago> pagos = new HashSet<Pago>(0);

	public Directorio() {
	}

	public Directorio(BigDecimal idDirectorio, BigDecimal montoAcuerdo) {
		this.idDirectorio = idDirectorio;
		this.montoAcuerdo = montoAcuerdo;
	}

	public Directorio(BigDecimal idDirectorio,
			UsuarioDetalle usuarioDetalleByFkUsudOri,
			UsuarioDetalle usuarioDetalleByFkUsudDes, BigDecimal montoAcuerdo,
			Set<Pago> pagos) {
		this.idDirectorio = idDirectorio;
		this.usuarioDetalleByFkUsudOri = usuarioDetalleByFkUsudOri;
		this.usuarioDetalleByFkUsudDes = usuarioDetalleByFkUsudDes;
		this.montoAcuerdo = montoAcuerdo;
		this.pagos = pagos;
	}

	@Id
	@Column(name = "ID_DIRECTORIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdDirectorio() {
		return this.idDirectorio;
	}

	public void setIdDirectorio(BigDecimal idDirectorio) {
		this.idDirectorio = idDirectorio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_USUD_ORI")
	public UsuarioDetalle getUsuarioDetalleByFkUsudOri() {
		return this.usuarioDetalleByFkUsudOri;
	}

	public void setUsuarioDetalleByFkUsudOri(
			UsuarioDetalle usuarioDetalleByFkUsudOri) {
		this.usuarioDetalleByFkUsudOri = usuarioDetalleByFkUsudOri;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_USUD_DES")
	public UsuarioDetalle getUsuarioDetalleByFkUsudDes() {
		return this.usuarioDetalleByFkUsudDes;
	}

	public void setUsuarioDetalleByFkUsudDes(
			UsuarioDetalle usuarioDetalleByFkUsudDes) {
		this.usuarioDetalleByFkUsudDes = usuarioDetalleByFkUsudDes;
	}

	@Column(name = "MONTO_ACUERDO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getMontoAcuerdo() {
		return this.montoAcuerdo;
	}

	public void setMontoAcuerdo(BigDecimal montoAcuerdo) {
		this.montoAcuerdo = montoAcuerdo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "directorio")
	public Set<Pago> getPagos() {
		return this.pagos;
	}

	public void setPagos(Set<Pago> pagos) {
		this.pagos = pagos;
	}

}
