package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "FACTURA", schema = "PRUEBAH")
@XmlRootElement(name = "factura")
public class Factura implements java.io.Serializable {

	private BigDecimal idFactura;
	private Pago pago;
	private Date fechaEmi;
	private String codigoFac;

	public Factura() {
	}

	public Factura(BigDecimal idFactura, Pago pago, Date fechaEmi,
			String codigoFac) {
		this.idFactura = idFactura;
		this.pago = pago;
		this.fechaEmi = fechaEmi;
		this.codigoFac = codigoFac;
	}

	@Id
	@Column(name = "ID_FACTURA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(BigDecimal idFactura) {
		this.idFactura = idFactura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PAGO", nullable = false)
	public Pago getPago() {
		return this.pago;
	}

	public void setPago(Pago pago) {
		this.pago = pago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_EMI", nullable = false, length = 7)
	public Date getFechaEmi() {
		return this.fechaEmi;
	}

	public void setFechaEmi(Date fechaEmi) {
		this.fechaEmi = fechaEmi;
	}

	@Column(name = "CODIGO_FAC", nullable = false, length = 40)
	public String getCodigoFac() {
		return this.codigoFac;
	}

	public void setCodigoFac(String codigoFac) {
		this.codigoFac = codigoFac;
	}

}
