package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "MONEDA", schema = "PRUEBAH")
@XmlRootElement(name = "moneda")
public class Moneda implements java.io.Serializable {

	private BigDecimal idMoneda;
	private Pais pais;
	private String nombre;
	private String signoMoneda;
	private Set<UsuarioMoneda> usuarioMonedas = new HashSet<UsuarioMoneda>(0);

	public Moneda() {
	}

	public Moneda(BigDecimal idMoneda, Pais pais, String nombre,
			String signoMoneda) {
		this.idMoneda = idMoneda;
		this.pais = pais;
		this.nombre = nombre;
		this.signoMoneda = signoMoneda;
	}

	public Moneda(BigDecimal idMoneda, Pais pais, String nombre,
			String signoMoneda, Set<UsuarioMoneda> usuarioMonedas) {
		this.idMoneda = idMoneda;
		this.pais = pais;
		this.nombre = nombre;
		this.signoMoneda = signoMoneda;
		this.usuarioMonedas = usuarioMonedas;
	}

	@Id
	@Column(name = "ID_MONEDA", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(BigDecimal idMoneda) {
		this.idMoneda = idMoneda;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_PAIS", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "SIGNO_MONEDA", nullable = false, length = 4)
	public String getSignoMoneda() {
		return this.signoMoneda;
	}

	public void setSignoMoneda(String signoMoneda) {
		this.signoMoneda = signoMoneda;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moneda")
	public Set<UsuarioMoneda> getUsuarioMonedas() {
		return this.usuarioMonedas;
	}

	public void setUsuarioMonedas(Set<UsuarioMoneda> usuarioMonedas) {
		this.usuarioMonedas = usuarioMonedas;
	}

}
