package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Pago generated by hbm2java
 */
@Entity
@Table(name = "PAGO", schema = "PRUEBAH")
@XmlRootElement(name = "pago")
public class Pago implements java.io.Serializable {

	private BigDecimal idPago;
	private Credito credito;
	private Directorio directorio;
	private BigDecimal monto;
	private Set<Factura> facturas = new HashSet<Factura>(0);

	public Pago() {
	}

	public Pago(BigDecimal idPago, Credito credito, Directorio directorio,
			BigDecimal monto) {
		this.idPago = idPago;
		this.credito = credito;
		this.directorio = directorio;
		this.monto = monto;
	}

	public Pago(BigDecimal idPago, Credito credito, Directorio directorio,
			BigDecimal monto, Set<Factura> facturas) {
		this.idPago = idPago;
		this.credito = credito;
		this.directorio = directorio;
		this.monto = monto;
		this.facturas = facturas;
	}

	@Id
	@Column(name = "ID_PAGO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPago() {
		return this.idPago;
	}

	public void setIdPago(BigDecimal idPago) {
		this.idPago = idPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_CREDITO", nullable = false)
	public Credito getCredito() {
		return this.credito;
	}

	public void setCredito(Credito credito) {
		this.credito = credito;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_DIRECTORIO", nullable = false)
	public Directorio getDirectorio() {
		return this.directorio;
	}

	public void setDirectorio(Directorio directorio) {
		this.directorio = directorio;
	}

	@Column(name = "MONTO", nullable = false, precision = 22, scale = 0)
	public BigDecimal getMonto() {
		return this.monto;
	}

	public void setMonto(BigDecimal monto) {
		this.monto = monto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pago")
	public Set<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(Set<Factura> facturas) {
		this.facturas = facturas;
	}

}
