package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "PAIS", schema = "PRUEBAH")
@XmlRootElement(name = "pais")
public class Pais implements java.io.Serializable {

	private BigDecimal idPais;
	private String nombre;
	private Set<Moneda> monedas = new HashSet<Moneda>(0);

	public Pais() {
	}

	public Pais(BigDecimal idPais, String nombre) {
		this.idPais = idPais;
		this.nombre = nombre;
	}

	public Pais(BigDecimal idPais, String nombre, Set<Moneda> monedas) {
		this.idPais = idPais;
		this.nombre = nombre;
		this.monedas = monedas;
	}

	@Id
	@Column(name = "ID_PAIS", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPais() {
		return this.idPais;
	}

	public void setIdPais(BigDecimal idPais) {
		this.idPais = idPais;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Moneda> getMonedas() {
		return this.monedas;
	}

	public void setMonedas(Set<Moneda> monedas) {
		this.monedas = monedas;
	}

}
