package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "PRUEBAH", uniqueConstraints = @UniqueConstraint(columnNames = "USUARIO"))
@XmlRootElement(name = "usuario")
public class Usuario implements java.io.Serializable {

	private BigDecimal idUsuario;
	private Rol rol;
	private String usuario;
	private String clave;
	private String tipo;
	private String correo;
	private Set<Token> tokens = new HashSet<Token>(0);
	private Set<UsuarioDetalle> usuarioDetalles = new HashSet<UsuarioDetalle>(0);

	public Usuario() {
	}

	public Usuario(BigDecimal idUsuario, Rol rol, String usuario, String clave,
			String tipo, String correo) {
		this.idUsuario = idUsuario;
		this.rol = rol;
		this.usuario = usuario;
		this.clave = clave;
		this.tipo = tipo;
		this.correo = correo;
	}

	public Usuario(BigDecimal idUsuario, Rol rol, String usuario, String clave,
			String tipo, String correo, Set<Token> tokens,
			Set<UsuarioDetalle> usuarioDetalles) {
		this.idUsuario = idUsuario;
		this.rol = rol;
		this.usuario = usuario;
		this.clave = clave;
		this.tipo = tipo;
		this.correo = correo;
		this.tokens = tokens;
		this.usuarioDetalles = usuarioDetalles;
	}

	@Id
	@Column(name = "ID_USUARIO", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(BigDecimal idUsuario) {
		this.idUsuario = idUsuario;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_ROL", nullable = false)
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@Column(name = "USUARIO", unique = true, nullable = false, length = 40)
	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CLAVE", nullable = false, length = 40)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "TIPO", nullable = false, length = 40)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "CORREO", nullable = false, length = 20)
	public String getCorreo() {
		return this.correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Token> getTokens() {
		return this.tokens;
	}

	public void setTokens(Set<Token> tokens) {
		this.tokens = tokens;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioDetalle> getUsuarioDetalles() {
		return this.usuarioDetalles;
	}

	public void setUsuarioDetalles(Set<UsuarioDetalle> usuarioDetalles) {
		this.usuarioDetalles = usuarioDetalles;
	}

}
