package entidad;

// Generated Sep 14, 2015 4:50:05 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * UsuarioDetalle generated by hbm2java
 */
@Entity
@Table(name = "USUARIO_DETALLE", schema = "PRUEBAH")
@XmlRootElement(name = "usuarioDetalle")
public class UsuarioDetalle implements java.io.Serializable {

	private BigDecimal idUsudetalle;
	private Usuario usuario;
	private String nombre;
	private String apellido;
	private String numeroIden;
	private String codigoIden;
	private String ubicacion;
	private Set<Directorio> directoriosForFkUsudDes = new HashSet<Directorio>(0);
	private Set<Credito> creditos = new HashSet<Credito>(0);
	private Set<Directorio> directoriosForFkUsudOri = new HashSet<Directorio>(0);
	private Set<UsuarioMoneda> usuarioMonedas = new HashSet<UsuarioMoneda>(0);

	public UsuarioDetalle() {
	}

	public UsuarioDetalle(BigDecimal idUsudetalle, Usuario usuario,
			String nombre, String numeroIden, String codigoIden) {
		this.idUsudetalle = idUsudetalle;
		this.usuario = usuario;
		this.nombre = nombre;
		this.numeroIden = numeroIden;
		this.codigoIden = codigoIden;
	}

	public UsuarioDetalle(BigDecimal idUsudetalle, Usuario usuario,
			String nombre, String apellido, String numeroIden,
			String codigoIden, String ubicacion,
			Set<Directorio> directoriosForFkUsudDes, Set<Credito> creditos,
			Set<Directorio> directoriosForFkUsudOri,
			Set<UsuarioMoneda> usuarioMonedas) {
		this.idUsudetalle = idUsudetalle;
		this.usuario = usuario;
		this.nombre = nombre;
		this.apellido = apellido;
		this.numeroIden = numeroIden;
		this.codigoIden = codigoIden;
		this.ubicacion = ubicacion;
		this.directoriosForFkUsudDes = directoriosForFkUsudDes;
		this.creditos = creditos;
		this.directoriosForFkUsudOri = directoriosForFkUsudOri;
		this.usuarioMonedas = usuarioMonedas;
	}

	@Id
	@Column(name = "ID_USUDETALLE", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdUsudetalle() {
		return this.idUsudetalle;
	}

	public void setIdUsudetalle(BigDecimal idUsudetalle) {
		this.idUsudetalle = idUsudetalle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FK_USUARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "NOMBRE", nullable = false, length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO", length = 40)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "NUMERO_IDEN", nullable = false, length = 40)
	public String getNumeroIden() {
		return this.numeroIden;
	}

	public void setNumeroIden(String numeroIden) {
		this.numeroIden = numeroIden;
	}

	@Column(name = "CODIGO_IDEN", nullable = false, length = 40)
	public String getCodigoIden() {
		return this.codigoIden;
	}

	public void setCodigoIden(String codigoIden) {
		this.codigoIden = codigoIden;
	}

	@Column(name = "UBICACION", length = 40)
	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioDetalleByFkUsudDes")
	public Set<Directorio> getDirectoriosForFkUsudDes() {
		return this.directoriosForFkUsudDes;
	}

	public void setDirectoriosForFkUsudDes(
			Set<Directorio> directoriosForFkUsudDes) {
		this.directoriosForFkUsudDes = directoriosForFkUsudDes;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioDetalle")
	public Set<Credito> getCreditos() {
		return this.creditos;
	}

	public void setCreditos(Set<Credito> creditos) {
		this.creditos = creditos;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioDetalleByFkUsudOri")
	public Set<Directorio> getDirectoriosForFkUsudOri() {
		return this.directoriosForFkUsudOri;
	}

	public void setDirectoriosForFkUsudOri(
			Set<Directorio> directoriosForFkUsudOri) {
		this.directoriosForFkUsudOri = directoriosForFkUsudOri;
	}
	@XmlTransient
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioDetalle")
	public Set<UsuarioMoneda> getUsuarioMonedas() {
		return this.usuarioMonedas;
	}

	public void setUsuarioMonedas(Set<UsuarioMoneda> usuarioMonedas) {
		this.usuarioMonedas = usuarioMonedas;
	}

}
